### ISSUE TITLE
Is it functional ? 

### ISSUE THREAD

**Issue by SteakdeNiche** [PeteyRev/js-match-height#1]
I tried to install: `npm i --save js-match-height`
Imported in a .js file: `import { MatchHeight } from 'js-match-height'`
Tried to log MatchHeight content and it seems to be an empty js object : {}

**Comment by PeteyRev** [comment]
@SteakdeNiche Hi, sorry I have fixed this in the newest version, should work great now! Please let me know if you have any more problems, or feature requests

**Comment by SteakdeNiche** [comment]
@PeteyRev thx for your quick answer, gonna take a look soon and let you know.
